# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - cargo fmt
  clippy:
    cmds:
      - cargo clippy --fix 
  format:
    cmds:
      - cargo fmt --all --check

  watch:
    cmds:
      - cargo watch -x run
  
  